export interface CropDatasetEntry {
  id: number;
  common_name: string;
  display_name: string;
  scientific_name: string;
  category: string;
  planting_season: string;
  harvest_start_days: number;
  harvest_end_days: number;
  temperature_min_c: number;
  temperature_max_c: number;
  optimal_temperature_c: number;
  altitude_min_m: number;
  altitude_max_m: number;
  soil_ph_min: number;
  soil_ph_max: number;
  water_mm_per_week: number;
  sunlight: string;
  lifecycle: string;
  yield_kg_per_hectare: number;
  farmgate_price_jmd_per_kg: number;
  wholesale_price_jmd_per_kg: number;
  retail_price_jmd_per_kg: number;
}

export const CROPS: CropDatasetEntry[] = [
  {
    "id": 1,
    "common_name": "ackee",
    "display_name": "Ackee",
    "scientific_name": "Blighia sapida",
    "category": "tree_fruit",
    "planting_season": "year_round",
    "harvest_start_days": 1095,
    "harvest_end_days": 1460,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 900,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 8000,
    "farmgate_price_jmd_per_kg": 350,
    "wholesale_price_jmd_per_kg": 500,
    "retail_price_jmd_per_kg": 900
  },
  {
    "id": 2,
    "common_name": "banana",
    "display_name": "Banana",
    "scientific_name": "Musa spp.",
    "category": "fruit",
    "planting_season": "year_round",
    "harvest_start_days": 270,
    "harvest_end_days": 365,
    "temperature_min_c": 24,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 600,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 40,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 35000,
    "farmgate_price_jmd_per_kg": 120,
    "wholesale_price_jmd_per_kg": 180,
    "retail_price_jmd_per_kg": 320
  },
  {
    "id": 3,
    "common_name": "plantain",
    "display_name": "Plantain",
    "scientific_name": "Musa paradisiaca",
    "category": "fruit",
    "planting_season": "year_round",
    "harvest_start_days": 300,
    "harvest_end_days": 420,
    "temperature_min_c": 24,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 800,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 40,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 30000,
    "farmgate_price_jmd_per_kg": 160,
    "wholesale_price_jmd_per_kg": 250,
    "retail_price_jmd_per_kg": 450
  },
  {
    "id": 4,
    "common_name": "coffee",
    "display_name": "Coffee",
    "scientific_name": "Coffea arabica",
    "category": "export_crop",
    "planting_season": "Sep-Nov",
    "harvest_start_days": 1095,
    "harvest_end_days": 1460,
    "temperature_min_c": 16,
    "temperature_max_c": 24,
    "optimal_temperature_c": 20,
    "altitude_min_m": 600,
    "altitude_max_m": 1700,
    "soil_ph_min": 5.0,
    "soil_ph_max": 6.5,
    "water_mm_per_week": 20,
    "sunlight": "partial_shade",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 2000,
    "farmgate_price_jmd_per_kg": 1200,
    "wholesale_price_jmd_per_kg": 1800,
    "retail_price_jmd_per_kg": 4000
  },
  {
    "id": 5,
    "common_name": "pimento",
    "display_name": "Pimento",
    "scientific_name": "Pimenta dioica",
    "category": "spice_crop",
    "planting_season": "Apr-Jun",
    "harvest_start_days": 1460,
    "harvest_end_days": 1825,
    "temperature_min_c": 20,
    "temperature_max_c": 30,
    "optimal_temperature_c": 25,
    "altitude_min_m": 100,
    "altitude_max_m": 1000,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 1500,
    "farmgate_price_jmd_per_kg": 900,
    "wholesale_price_jmd_per_kg": 1300,
    "retail_price_jmd_per_kg": 2500
  },
  {
    "id": 6,
    "common_name": "cocoa",
    "display_name": "Cocoa",
    "scientific_name": "Theobroma cacao",
    "category": "export_crop",
    "planting_season": "year_round",
    "harvest_start_days": 1095,
    "harvest_end_days": 1460,
    "temperature_min_c": 21,
    "temperature_max_c": 30,
    "optimal_temperature_c": 26,
    "altitude_min_m": 0,
    "altitude_max_m": 800,
    "soil_ph_min": 5.0,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 30,
    "sunlight": "partial_shade",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 1200,
    "farmgate_price_jmd_per_kg": 600,
    "wholesale_price_jmd_per_kg": 900,
    "retail_price_jmd_per_kg": 2000
  },
  {
    "id": 7,
    "common_name": "coconut",
    "display_name": "Coconut",
    "scientific_name": "Cocos nucifera",
    "category": "tree_crop",
    "planting_season": "year_round",
    "harvest_start_days": 1825,
    "harvest_end_days": 2555,
    "temperature_min_c": 24,
    "temperature_max_c": 32,
    "optimal_temperature_c": 28,
    "altitude_min_m": 0,
    "altitude_max_m": 300,
    "soil_ph_min": 5.5,
    "soil_ph_max": 8.0,
    "water_mm_per_week": 25,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 15000,
    "farmgate_price_jmd_per_kg": 80,
    "wholesale_price_jmd_per_kg": 120,
    "retail_price_jmd_per_kg": 250
  },

  {
    "id": 8,
    "common_name": "breadfruit",
    "display_name": "Breadfruit",
    "scientific_name": "Artocarpus altilis",
    "category": "tree_fruit",
    "planting_season": "year_round",
    "harvest_start_days": 1460,
    "harvest_end_days": 1825,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 600,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 10000,
    "farmgate_price_jmd_per_kg": 180,
    "wholesale_price_jmd_per_kg": 260,
    "retail_price_jmd_per_kg": 500
  },
  {
    "id": 9,
    "common_name": "mango",
    "display_name": "Mango",
    "scientific_name": "Mangifera indica",
    "category": "tree_fruit",
    "planting_season": "year_round",
    "harvest_start_days": 1095,
    "harvest_end_days": 1825,
    "temperature_min_c": 22,
    "temperature_max_c": 34,
    "optimal_temperature_c": 28,
    "altitude_min_m": 0,
    "altitude_max_m": 1000,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 12000,
    "farmgate_price_jmd_per_kg": 200,
    "wholesale_price_jmd_per_kg": 320,
    "retail_price_jmd_per_kg": 600
  },
  {
    "id": 10,
    "common_name": "guava",
    "display_name": "Guava",
    "scientific_name": "Psidium guajava",
    "category": "fruit",
    "planting_season": "year_round",
    "harvest_start_days": 730,
    "harvest_end_days": 1095,
    "temperature_min_c": 20,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.0,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 10000,
    "farmgate_price_jmd_per_kg": 180,
    "wholesale_price_jmd_per_kg": 280,
    "retail_price_jmd_per_kg": 520
  },

  {
    "id": 11,
    "common_name": "soursop",
    "display_name": "Soursop",
    "scientific_name": "Annona muricata",
    "category": "fruit",
    "planting_season": "year_round",
    "harvest_start_days": 730,
    "harvest_end_days": 1095,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 800,
    "soil_ph_min": 5.5,
    "soil_ph_max": 6.5,
    "water_mm_per_week": 25,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 9000,
    "farmgate_price_jmd_per_kg": 300,
    "wholesale_price_jmd_per_kg": 450,
    "retail_price_jmd_per_kg": 800
  },
  {
    "id": 12,
    "common_name": "papaya",
    "display_name": "Papaya",
    "scientific_name": "Carica papaya",
    "category": "fruit",
    "planting_season": "year_round",
    "harvest_start_days": 240,
    "harvest_end_days": 365,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 800,
    "soil_ph_min": 6.0,
    "soil_ph_max": 6.8,
    "water_mm_per_week": 25,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 25000,
    "farmgate_price_jmd_per_kg": 150,
    "wholesale_price_jmd_per_kg": 220,
    "retail_price_jmd_per_kg": 400
  },

  {
    "id": 13,
    "common_name": "pineapple",
    "display_name": "Pineapple",
    "scientific_name": "Ananas comosus",
    "category": "fruit",
    "planting_season": "year_round",
    "harvest_start_days": 420,
    "harvest_end_days": 540,
    "temperature_min_c": 20,
    "temperature_max_c": 32,
    "optimal_temperature_c": 26,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 4.5,
    "soil_ph_max": 6.5,
    "water_mm_per_week": 15,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 30000,
    "farmgate_price_jmd_per_kg": 200,
    "wholesale_price_jmd_per_kg": 320,
    "retail_price_jmd_per_kg": 600
  },

  {
    "id": 14,
    "common_name": "watermelon",
    "display_name": "Watermelon",
    "scientific_name": "Citrullus lanatus",
    "category": "fruit",
    "planting_season": "Nov-Feb;Jul-Sep",
    "harvest_start_days": 75,
    "harvest_end_days": 100,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 30000,
    "farmgate_price_jmd_per_kg": 120,
    "wholesale_price_jmd_per_kg": 180,
    "retail_price_jmd_per_kg": 320
  },

  {
    "id": 15,
    "common_name": "pumpkin",
    "display_name": "Pumpkin",
    "scientific_name": "Cucurbita moschata",
    "category": "vegetable",
    "planting_season": "year_round",
    "harvest_start_days": 90,
    "harvest_end_days": 120,
    "temperature_min_c": 20,
    "temperature_max_c": 32,
    "optimal_temperature_c": 26,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.8,
    "soil_ph_max": 7.2,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 20000,
    "farmgate_price_jmd_per_kg": 150,
    "wholesale_price_jmd_per_kg": 240,
    "retail_price_jmd_per_kg": 420
  },

  {
    "id": 16,
    "common_name": "tomato",
    "display_name": "Tomato",
    "scientific_name": "Solanum lycopersicum",
    "category": "vegetable",
    "planting_season": "Oct-Feb;May-Jul",
    "harvest_start_days": 75,
    "harvest_end_days": 120,
    "temperature_min_c": 18,
    "temperature_max_c": 30,
    "optimal_temperature_c": 24,
    "altitude_min_m": 0,
    "altitude_max_m": 1500,
    "soil_ph_min": 5.8,
    "soil_ph_max": 6.8,
    "water_mm_per_week": 25,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 25000,
    "farmgate_price_jmd_per_kg": 280,
    "wholesale_price_jmd_per_kg": 400,
    "retail_price_jmd_per_kg": 650
  },

  {
    "id": 17,
    "common_name": "callaloo",
    "display_name": "Callaloo",
    "scientific_name": "Amaranthus spp.",
    "category": "leafy_green",
    "planting_season": "year_round",
    "harvest_start_days": 25,
    "harvest_end_days": 40,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 28,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 6.0,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 12000,
    "farmgate_price_jmd_per_kg": 120,
    "wholesale_price_jmd_per_kg": 200,
    "retail_price_jmd_per_kg": 350
  },

  {
    "id": 18,
    "common_name": "sweet_potato",
    "display_name": "Sweet Potato",
    "scientific_name": "Ipomoea batatas",
    "category": "root_crop",
    "planting_season": "year_round",
    "harvest_start_days": 90,
    "harvest_end_days": 150,
    "temperature_min_c": 21,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 6.8,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 20000,
    "farmgate_price_jmd_per_kg": 220,
    "wholesale_price_jmd_per_kg": 320,
    "retail_price_jmd_per_kg": 550
  },

  {
    "id": 19,
    "common_name": "yam",
    "display_name": "Yam",
    "scientific_name": "Dioscorea spp.",
    "category": "root_crop",
    "planting_season": "Apr-Jun",
    "harvest_start_days": 240,
    "harvest_end_days": 330,
    "temperature_min_c": 22,
    "temperature_max_c": 30,
    "optimal_temperature_c": 26,
    "altitude_min_m": 0,
    "altitude_max_m": 1000,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 18000,
    "farmgate_price_jmd_per_kg": 350,
    "wholesale_price_jmd_per_kg": 600,
    "retail_price_jmd_per_kg": 1000
  },

  {
    "id": 20,
    "common_name": "cassava",
    "display_name": "Cassava",
    "scientific_name": "Manihot esculenta",
    "category": "root_crop",
    "planting_season": "Apr-Jun;Sep-Nov",
    "harvest_start_days": 240,
    "harvest_end_days": 360,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 15,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 15000,
    "farmgate_price_jmd_per_kg": 120,
    "wholesale_price_jmd_per_kg": 200,
    "retail_price_jmd_per_kg": 350
  },

  {
    "id": 21,
    "common_name": "dasheen",
    "display_name": "Dasheen",
    "scientific_name": "Colocasia esculenta",
    "category": "root_crop",
    "planting_season": "Apr-Jun;Sep-Nov",
    "harvest_start_days": 180,
    "harvest_end_days": 270,
    "temperature_min_c": 21,
    "temperature_max_c": 30,
    "optimal_temperature_c": 26,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 35,
    "sunlight": "partial_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 16000,
    "farmgate_price_jmd_per_kg": 300,
    "wholesale_price_jmd_per_kg": 450,
    "retail_price_jmd_per_kg": 750
  },

  {
    "id": 22,
    "common_name": "ginger",
    "display_name": "Ginger",
    "scientific_name": "Zingiber officinale",
    "category": "spice_crop",
    "planting_season": "Apr-Jun",
    "harvest_start_days": 210,
    "harvest_end_days": 270,
    "temperature_min_c": 20,
    "temperature_max_c": 30,
    "optimal_temperature_c": 25,
    "altitude_min_m": 100,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 6.5,
    "water_mm_per_week": 25,
    "sunlight": "partial_shade",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 15000,
    "farmgate_price_jmd_per_kg": 600,
    "wholesale_price_jmd_per_kg": 850,
    "retail_price_jmd_per_kg": 1200
  },

  {
    "id": 23,
    "common_name": "turmeric",
    "display_name": "Turmeric",
    "scientific_name": "Curcuma longa",
    "category": "spice_crop",
    "planting_season": "Apr-Jun",
    "harvest_start_days": 240,
    "harvest_end_days": 300,
    "temperature_min_c": 20,
    "temperature_max_c": 30,
    "optimal_temperature_c": 25,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 25,
    "sunlight": "partial_shade",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 14000,
    "farmgate_price_jmd_per_kg": 350,
    "wholesale_price_jmd_per_kg": 520,
    "retail_price_jmd_per_kg": 900
  },

  {
    "id": 24,
    "common_name": "hot_pepper_scotch_bonnet",
    "display_name": "Scotch Bonnet Pepper",
    "scientific_name": "Capsicum chinense",
    "category": "vegetable",
    "planting_season": "year_round",
    "harvest_start_days": 90,
    "harvest_end_days": 150,
    "temperature_min_c": 22,
    "temperature_max_c": 32,
    "optimal_temperature_c": 28,
    "altitude_min_m": 0,
    "altitude_max_m": 900,
    "soil_ph_min": 5.5,
    "soil_ph_max": 6.8,
    "water_mm_per_week": 25,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 10000,
    "farmgate_price_jmd_per_kg": 700,
    "wholesale_price_jmd_per_kg": 1000,
    "retail_price_jmd_per_kg": 1500
  },

  {
    "id": 25,
    "common_name": "okra",
    "display_name": "Okra",
    "scientific_name": "Abelmoschus esculentus",
    "category": "vegetable",
    "planting_season": "year_round",
    "harvest_start_days": 50,
    "harvest_end_days": 70,
    "temperature_min_c": 22,
    "temperature_max_c": 34,
    "optimal_temperature_c": 28,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 6.0,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 20,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 12000,
    "farmgate_price_jmd_per_kg": 180,
    "wholesale_price_jmd_per_kg": 280,
    "retail_price_jmd_per_kg": 500
  },

  {
    "id": 26,
    "common_name": "thyme",
    "display_name": "Thyme",
    "scientific_name": "Thymus vulgaris",
    "category": "herb",
    "planting_season": "year_round",
    "harvest_start_days": 90,
    "harvest_end_days": 120,
    "temperature_min_c": 18,
    "temperature_max_c": 28,
    "optimal_temperature_c": 23,
    "altitude_min_m": 0,
    "altitude_max_m": 1500,
    "soil_ph_min": 6.0,
    "soil_ph_max": 8.0,
    "water_mm_per_week": 10,
    "sunlight": "full_sun",
    "lifecycle": "perennial",
    "yield_kg_per_hectare": 5000,
    "farmgate_price_jmd_per_kg": 700,
    "wholesale_price_jmd_per_kg": 1100,
    "retail_price_jmd_per_kg": 1800
  },

  {
    "id": 27,
    "common_name": "scallion",
    "display_name": "Scallion",
    "scientific_name": "Allium fistulosum",
    "category": "herb",
    "planting_season": "year_round",
    "harvest_start_days": 60,
    "harvest_end_days": 90,
    "temperature_min_c": 18,
    "temperature_max_c": 28,
    "optimal_temperature_c": 23,
    "altitude_min_m": 0,
    "altitude_max_m": 1500,
    "soil_ph_min": 6.0,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 15,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 10000,
    "farmgate_price_jmd_per_kg": 220,
    "wholesale_price_jmd_per_kg": 350,
    "retail_price_jmd_per_kg": 650
  },

  {
    "id": 28,
    "common_name": "sorrel",
    "display_name": "Sorrel",
    "scientific_name": "Hibiscus sabdariffa",
    "category": "beverage_crop",
    "planting_season": "May-Jul",
    "harvest_start_days": 150,
    "harvest_end_days": 210,
    "temperature_min_c": 20,
    "temperature_max_c": 32,
    "optimal_temperature_c": 27,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 7.5,
    "water_mm_per_week": 15,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 8000,
    "farmgate_price_jmd_per_kg": 250,
    "wholesale_price_jmd_per_kg": 400,
    "retail_price_jmd_per_kg": 800
  },

  {
    "id": 29,
    "common_name": "peanut",
    "display_name": "Peanut",
    "scientific_name": "Arachis hypogaea",
    "category": "legume",
    "planting_season": "May-Jul;Sep-Nov",
    "harvest_start_days": 110,
    "harvest_end_days": 150,
    "temperature_min_c": 20,
    "temperature_max_c": 30,
    "optimal_temperature_c": 25,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.5,
    "soil_ph_max": 6.8,
    "water_mm_per_week": 15,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 3000,
    "farmgate_price_jmd_per_kg": 280,
    "wholesale_price_jmd_per_kg": 420,
    "retail_price_jmd_per_kg": 750
  },

  {
    "id": 30,
    "common_name": "gungo_pea",
    "display_name": "Gungo Pea",
    "scientific_name": "Cajanus cajan",
    "category": "legume",
    "planting_season": "May-Jul",
    "harvest_start_days": 150,
    "harvest_end_days": 240,
    "temperature_min_c": 20,
    "temperature_max_c": 32,
    "optimal_temperature_c": 26,
    "altitude_min_m": 0,
    "altitude_max_m": 1200,
    "soil_ph_min": 5.0,
    "soil_ph_max": 7.0,
    "water_mm_per_week": 10,
    "sunlight": "full_sun",
    "lifecycle": "annual",
    "yield_kg_per_hectare": 4000,
    "farmgate_price_jmd_per_kg": 180,
    "wholesale_price_jmd_per_kg": 280,
    "retail_price_jmd_per_kg": 500
  }
]
