import { CropType } from './types';

/** Weekday numbers (0 = Sunday, 1 = Monday, ... 6 = Saturday) that are valid contract delivery days. */
export const CONTRACT_DELIVERY_DAYS: number[] = [0, 1];

/** Days from planting to first harvest (harvest_start_days from jamaican_crops.json). */
export const CROP_DAYS_TO_HARVEST: Record<CropType, number> = {
  [CropType.ACKEE]: 1095,
  [CropType.BANANA]: 270,
  [CropType.PLANTAIN]: 300,
  [CropType.COFFEE]: 1095,
  [CropType.PIMENTO]: 1460,
  [CropType.COCOA]: 1095,
  [CropType.COCONUT]: 1825,
  [CropType.BREADFRUIT]: 1460,
  [CropType.MANGO]: 1095,
  [CropType.GUAVA]: 730,
  [CropType.SOURSOP]: 730,
  [CropType.PAPAYA]: 240,
  [CropType.PINEAPPLE]: 420,
  [CropType.WATERMELON]: 75,
  [CropType.PUMPKIN]: 90,
  [CropType.TOMATO]: 75,
  [CropType.CALLALOO]: 25,
  [CropType.SWEET_POTATO]: 90,
  [CropType.YAM]: 240,
  [CropType.CASSAVA]: 240,
  [CropType.DASHEEN]: 180,
  [CropType.GINGER]: 210,
  [CropType.TURMERIC]: 240,
  [CropType.HOT_PEPPER_SCOTCH_BONNET]: 90,
  [CropType.OKRA]: 50,
  [CropType.THYME]: 90,
  [CropType.SCALLION]: 60,
  [CropType.SORREL]: 150,
  [CropType.PEANUT]: 110,
  [CropType.GUNGO_PEA]: 150,
};

/** Yield kg per acre (from jamaican_crops.json yield_kg_per_hectare / 2.471). */
export const CROP_YIELD_PER_ACRE: Record<CropType, number> = {
  [CropType.ACKEE]: 3240,
  [CropType.BANANA]: 14175,
  [CropType.PLANTAIN]: 12150,
  [CropType.COFFEE]: 810,
  [CropType.PIMENTO]: 607,
  [CropType.COCOA]: 486,
  [CropType.COCONUT]: 6075,
  [CropType.BREADFRUIT]: 4050,
  [CropType.MANGO]: 4860,
  [CropType.GUAVA]: 4050,
  [CropType.SOURSOP]: 3645,
  [CropType.PAPAYA]: 10125,
  [CropType.PINEAPPLE]: 12150,
  [CropType.WATERMELON]: 12150,
  [CropType.PUMPKIN]: 8100,
  [CropType.TOMATO]: 10125,
  [CropType.CALLALOO]: 4860,
  [CropType.SWEET_POTATO]: 8100,
  [CropType.YAM]: 7290,
  [CropType.CASSAVA]: 6075,
  [CropType.DASHEEN]: 6480,
  [CropType.GINGER]: 6075,
  [CropType.TURMERIC]: 5670,
  [CropType.HOT_PEPPER_SCOTCH_BONNET]: 4050,
  [CropType.OKRA]: 4860,
  [CropType.THYME]: 2025,
  [CropType.SCALLION]: 4050,
  [CropType.SORREL]: 3240,
  [CropType.PEANUT]: 1215,
  [CropType.GUNGO_PEA]: 1620,
};

export const CROP_UNIT: Record<CropType, string> = {
  [CropType.ACKEE]: 'kg',
  [CropType.BANANA]: 'kg',
  [CropType.PLANTAIN]: 'kg',
  [CropType.COFFEE]: 'kg',
  [CropType.PIMENTO]: 'kg',
  [CropType.COCOA]: 'kg',
  [CropType.COCONUT]: 'kg',
  [CropType.BREADFRUIT]: 'kg',
  [CropType.MANGO]: 'kg',
  [CropType.GUAVA]: 'kg',
  [CropType.SOURSOP]: 'kg',
  [CropType.PAPAYA]: 'kg',
  [CropType.PINEAPPLE]: 'kg',
  [CropType.WATERMELON]: 'kg',
  [CropType.PUMPKIN]: 'kg',
  [CropType.TOMATO]: 'kg',
  [CropType.CALLALOO]: 'kg',
  [CropType.SWEET_POTATO]: 'kg',
  [CropType.YAM]: 'kg',
  [CropType.CASSAVA]: 'kg',
  [CropType.DASHEEN]: 'kg',
  [CropType.GINGER]: 'kg',
  [CropType.TURMERIC]: 'kg',
  [CropType.HOT_PEPPER_SCOTCH_BONNET]: 'kg',
  [CropType.OKRA]: 'kg',
  [CropType.THYME]: 'kg',
  [CropType.SCALLION]: 'kg',
  [CropType.SORREL]: 'kg',
  [CropType.PEANUT]: 'kg',
  [CropType.GUNGO_PEA]: 'kg',
};

/** Display names from jamaican_crops.json. */
export const CROP_LABELS: Record<CropType, string> = {
  [CropType.ACKEE]: 'Ackee',
  [CropType.BANANA]: 'Banana',
  [CropType.PLANTAIN]: 'Plantain',
  [CropType.COFFEE]: 'Coffee',
  [CropType.PIMENTO]: 'Pimento',
  [CropType.COCOA]: 'Cocoa',
  [CropType.COCONUT]: 'Coconut',
  [CropType.BREADFRUIT]: 'Breadfruit',
  [CropType.MANGO]: 'Mango',
  [CropType.GUAVA]: 'Guava',
  [CropType.SOURSOP]: 'Soursop',
  [CropType.PAPAYA]: 'Papaya',
  [CropType.PINEAPPLE]: 'Pineapple',
  [CropType.WATERMELON]: 'Watermelon',
  [CropType.PUMPKIN]: 'Pumpkin',
  [CropType.TOMATO]: 'Tomato',
  [CropType.CALLALOO]: 'Callaloo',
  [CropType.SWEET_POTATO]: 'Sweet Potato',
  [CropType.YAM]: 'Yam',
  [CropType.CASSAVA]: 'Cassava',
  [CropType.DASHEEN]: 'Dasheen',
  [CropType.GINGER]: 'Ginger',
  [CropType.TURMERIC]: 'Turmeric',
  [CropType.HOT_PEPPER_SCOTCH_BONNET]: 'Scotch Bonnet Pepper',
  [CropType.OKRA]: 'Okra',
  [CropType.THYME]: 'Thyme',
  [CropType.SCALLION]: 'Scallion',
  [CropType.SORREL]: 'Sorrel',
  [CropType.PEANUT]: 'Peanut',
  [CropType.GUNGO_PEA]: 'Gungo Pea',
};

export const CROP_EMOJI: Record<CropType, string> = {
  [CropType.ACKEE]: '🥘',
  [CropType.BANANA]: '🍌',
  [CropType.PLANTAIN]: '🍌',
  [CropType.COFFEE]: '☕',
  [CropType.PIMENTO]: '🫒',
  [CropType.COCOA]: '🍫',
  [CropType.COCONUT]: '🥥',
  [CropType.BREADFRUIT]: '🍞',
  [CropType.MANGO]: '🥭',
  [CropType.GUAVA]: '🍐',
  [CropType.SOURSOP]: '🍈',
  [CropType.PAPAYA]: '🍈',
  [CropType.PINEAPPLE]: '🍍',
  [CropType.WATERMELON]: '🍉',
  [CropType.PUMPKIN]: '🎃',
  [CropType.TOMATO]: '🍅',
  [CropType.CALLALOO]: '🥬',
  [CropType.SWEET_POTATO]: '🍠',
  [CropType.YAM]: '🍠',
  [CropType.CASSAVA]: '🥔',
  [CropType.DASHEEN]: '🥔',
  [CropType.GINGER]: '🫚',
  [CropType.TURMERIC]: '🫚',
  [CropType.HOT_PEPPER_SCOTCH_BONNET]: '🌶️',
  [CropType.OKRA]: '🥗',
  [CropType.THYME]: '🌿',
  [CropType.SCALLION]: '🌱',
  [CropType.SORREL]: '🌺',
  [CropType.PEANUT]: '🥜',
  [CropType.GUNGO_PEA]: '🫛',
};

/** Wholesale JMD per kg from jamaican_crops.json (reasonable market prices). */
export const CROP_WHOLESALE_JMD_PER_KG: Record<CropType, number> = {
  [CropType.ACKEE]: 500,
  [CropType.BANANA]: 180,
  [CropType.PLANTAIN]: 250,
  [CropType.COFFEE]: 1800,
  [CropType.PIMENTO]: 1300,
  [CropType.COCOA]: 900,
  [CropType.COCONUT]: 120,
  [CropType.BREADFRUIT]: 260,
  [CropType.MANGO]: 320,
  [CropType.GUAVA]: 280,
  [CropType.SOURSOP]: 450,
  [CropType.PAPAYA]: 220,
  [CropType.PINEAPPLE]: 320,
  [CropType.WATERMELON]: 180,
  [CropType.PUMPKIN]: 240,
  [CropType.TOMATO]: 400,
  [CropType.CALLALOO]: 200,
  [CropType.SWEET_POTATO]: 320,
  [CropType.YAM]: 600,
  [CropType.CASSAVA]: 200,
  [CropType.DASHEEN]: 450,
  [CropType.GINGER]: 850,
  [CropType.TURMERIC]: 520,
  [CropType.HOT_PEPPER_SCOTCH_BONNET]: 1000,
  [CropType.OKRA]: 280,
  [CropType.THYME]: 1100,
  [CropType.SCALLION]: 350,
  [CropType.SORREL]: 400,
  [CropType.PEANUT]: 420,
  [CropType.GUNGO_PEA]: 280,
};

/** All orders use price per kg and quantity in kg (JMD). */
export const PRICE_PER_KG_LABEL = 'J$/kg';

/** Exchange rate for USD display: 1 USD = JMD_PER_USD JMD. */
export const JMD_PER_USD = 157;
